### PR TITLE
Code Reorg and Simplification

### PR DESCRIPTION
**Pull request by victorhg**
Over the weeks, as we explore the project, a lot of code was added and I wanted to try to refactor as a way to understand what we are coding, but also reduce duplication that was creating a lot of complexity, and could slow us as we go to the last few weeks of the project.

Assuming that we will have to share this code with the university for scoring, this pull request aims to be the first step into:
- Reducing duplication. Multiple notebooks doing the same type of procedures in order to achieve results
- Removed multiple yolo models in different folder structures
- Renaming notebooks for better understanding of The Responsibility of each file
- Removed unnecessary notebooks we decided not to pursue (fast rcnn)

I also runed all the training and visualization notebooks to be sure still works.

There's still work to do (specially on duplicated code for augmentation and file operations). _this is the beginning_ :)

### CODE REVIEW

**Review by Fatimat01 — DISMISSED** [review]
some of the codes in the placed in the msaai library has changed to some extent due to auto annotation. In the code im not using the same method of augmentation for setcolor and bounding boxes as used in the custom train.

the train folder restructure is different from how its generated after the run. its generated in the same path as the notebook although i understand this can be moved after the run since we not submitting it. But like I said before, merging this to main is not a problem but I can already see the changes that will be overwritten after a new PR from another branch.

**Comment by victorhg** [comment]
I haven't changed the augmentation methods  and bounding boxes on the files original files. in both Train Custom and Code the code remains as the main codebase. 

Can you point to what/where augmentation has changed?

**Review by caliskate — CHANGES_REQUESTED** [review]
suggestions:
remove all notebooks we don't need after our meeting
ensure the notebook can run without a "settings.json" path error after datasets folder is created
condense video and functions to one notebook per model to more easily attach notebook(s) to final report

**Comment by victorhg** [comment]
Removed the files notebooks `code` and pre benchmark.

On the code we have on Main branch it is not possible for me to run the training without updating the setting.json. I had to change the yolo settings to run the main, otherwise would not run the same way on a Mac, with multiple errors. Will try, but not sure it is possible. 

not sure what last item means: remove the python file, and duplicate the code to the remaining notebooks? Video is already condensed on 1 file. Need more info here

**Pull request merged**
